FROM clojure:temurin-21-tools-deps-jammy
LABEL maintainer="Marc <xtof@relica.io>"

WORKDIR /usr/src/app

# For development, we don't copy files - they will be mounted as volumes
# in docker-compose.dev.yml for the shutter package
# This allows for hot reloading of all code changes

WORKDIR /usr/src/app/packages_clj/shutter

# Expose the application and nREPL ports
EXPOSE 2173
EXPOSE 7889

CMD ["clojure", "-M:dev"]