FROM clojure:temurin-21-tools-deps-jammy
MAINTAINER Marc <xtof@relica.io>

WORKDIR /usr/src/app/packages_clj/portal

COPY ./packages_clj/portal/deps.edn .
RUN clojure -P  # Download dependencies

COPY ./packages_clj/portal .

EXPOSE 8080

CMD ["clojure", "-M:dev"]
