version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: /bin/sh -c "redis-server --requirepass redis"
    volumes:
      - ./packages_ts/core/dataplex/data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - rlc-net

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    command: ["bash", "/docker-entrypoint-initdb.d/init-postgres.sh"]
    volumes:
      - ./packages_ts/core/dataplex/data/postgres:/var/lib/postgresql/data
      - ./packages_ts/core/dataplex/init_scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - rlc-net

  neo4j:
    container_name: neo4j
    image: neo4j:5.12.0
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted="apoc.*"
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*,gds.\\\*
      - dbms_connector_bolt_listen__address=neo4j-db:7687
      - dbms_connector_bolt_advertised__address=neo4j-db:7687
      - NEO4J_apoc_import_file_enabled="true"
      - NEO4J_apoc_export_file_enabled="true"
      - NEO4J_ACCEPT_LICENSE_AGREEMENT="yes"
    volumes:
      - ./packages_ts/core/dataplex/data/neo4j:/data
      - ./seed_csv:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cypher-shell -u neo4j -p password 'MATCH (n) RETURN COUNT(n);' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rlc-net

  archivist:
    container_name: archivist
    build:
      context: ./
      dockerfile: Dockerfile.archivist
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
    # command: ["yarn", "start:dev"]
    command: yarn dev --host 0.0.0.0
    volumes:
      - ./packages_ts/backend/archivist:/usr/src/app/packages_ts/backend/archivist
      - ./seed_xls:/usr/src/app/packages_ts/backend/archivist/seed_xls
      - ./seed_csv:/usr/src/app/packages_ts/backend/archivist/seed_csv
      - /usr/src/app/packages_ts/backend/archivist/node_modules
    ports:
      - "3000:3000"
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - rlc-net

  clarity-core:
    container_name: clarity-core
    # image: node:latest
    build:
      context: ./
      dockerfile: Dockerfile.clarity-core
    # working_dir: /usr/src/app
    restart: always
    # command: sh -c "npm install && npx tsc --outDir dist && npm start"
    # command: sh -c "yarn install && yarn dev"
    command: ["yarn", "start:dev"]
    volumes:
      - ./packages_ts/backend/clarity-core:/usr/src/app/packages_ts/backend/clarity-core
      - /usr/src/app/packages_ts/backend/clarity-core/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - archivist
    networks:
      rlc-net:
        aliases:
          - clarity-core

  knowledge-integrator:
    container_name: knowledge-integrator
    build:
      context: .
      dockerfile: Dockerfile.knowledge-integrator
    restart: always
    command: yarn dev
    volumes:
      - ./packages_ts/frontend/knowledge-integrator:/usr/src/app/packages_ts/frontend/knowledge-integrator
      - ./packages_ts/libs/constants:/usr/src/app/packages_ts/libs/constants
      - ./packages_ts/frontend/components/fact-search-ui:/usr/src/app/packages_ts/frontend/components/fact-search-ui
      - ./packages_ts/frontend/components/3d-graph-ui:/usr/src/app/packages_ts/frontend/components/3d-graph-ui
      - ./packages_ts/core/hsm-manager:/usr/src/app/packages_ts/core/hsm-manager
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - archivist
      - clarity-core
    networks:
      rlc-net:
        aliases:
          - knowledge-integrator

  clarity-clj:
    container_name: clarity-clj
    build:
      context: ./
      dockerfile: Dockerfile.clarity-clj
    restart: always
    command: ["clojure", "-M:dev"]
    # command: ["clojure", "-M:run"]
    volumes:
      - ./packages_clj/clarity:/usr/src/app/packages_clj/clarity
      - /usr/src/app/.m2
    ports:
      - "3002:3002"
      # nREPL port
      - "7888:7888"
      - "5555:5555"
    depends_on:
      - archivist
    networks:
      rlc-net:
        aliases:
          - clarity-clj

networks:
  rlc-net:
    name: rlc-net
    driver: bridge
