FROM node:latest as build
MAINTAINER Marc <marc@speculum-obscurum>

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

COPY packages_ts/libs/types ./packages_ts/libs/types
COPY packages_ts/libs/constants ./packages_ts/libs/constants

COPY packages_ts/config/tsconfig.base.json ./packages_ts/config/tsconfig.base.json
COPY packages_ts/config/tsconfig.lib.json ./packages_ts/config/tsconfig.lib.json

RUN yarn install --pure-lockfile --non-interactive

WORKDIR /usr/src/app/packages_ts/libs/types
RUN yarn build

WORKDIR /usr/src/app/packages_ts/libs/constants
RUN yarn build

# --------------------------------------

FROM clojure:temurin-17-tools-deps

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/packages_ts/config/tsconfig.base.json /usr/src/app/packages_ts/config/tsconfig.base.json
COPY --from=build /usr/src/app/packages_ts/config/tsconfig.lib.json /usr/src/app/packages_ts/config/tsconfig.lib.json

COPY --from=build /usr/src/app/packages_ts/libs/types/package.json /usr/src/app/packages_ts/libs/types/package.json
COPY --from=build /usr/src/app/packages_ts/libs/types/dist /usr/src/app/packages_ts/libs/types/dist

COPY --from=build /usr/src/app/packages_ts/libs/constants/package.json /usr/src/app/packages_ts/libs/constants/package.json
COPY --from=build /usr/src/app/packages_ts/libs/constants/dist /usr/src/app/packages_ts/libs/constants/dist

COPY packages_clj/clarity /usr/src/app/packages_clj/clarity

WORKDIR /usr/src/app/packages_clj/clarity

EXPOSE 3002
EXPOSE 7888  
# Expose nREPL port

# CMD ["clojure", "-M:run"]
# Use dev profile for development
CMD ["clojure", "-M:dev"]
