version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: /bin/sh -c "redis-server --requirepass redis"
    volumes:
      - ./packages/dataplex/data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - rlc-net

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    command: ["bash", "/docker-entrypoint-initdb.d/init-postgres.sh"]
    volumes:
      - ./packages/dataplex/data/postgres:/var/lib/postgresql/data
      - ./packages/dataplex/init_scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - rlc-net

  neo4j:
    container_name: neo4j
    image: neo4j:5.12.0
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted="apoc.*"
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*,gds.\\\*
      - dbms_connector_bolt_listen__address=neo4j-db:7687
      - dbms_connector_bolt_advertised__address=neo4j-db:7687
      - NEO4J_apoc_import_file_enabled="true"
      - NEO4J_apoc_export_file_enabled="true"
      - NEO4J_ACCEPT_LICENSE_AGREEMENT="yes"
    volumes:
      - ./packages/dataplex/data/neo4j:/data
      - ./seed_csv:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cypher-shell -u neo4j -p password 'MATCH (n) RETURN COUNT(n);' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rlc-net

  archivist:
    container_name: archivist
    build:
      context: ./
      dockerfile: Dockerfile.archivist
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
    command: ["yarn", "start:dev"]
    volumes:
      - ./packages/archivist:/usr/src/app/packages/archivist
      - ./seed_xls:/usr/src/app/packages/archivist/seed_xls
      - ./seed_csv:/usr/src/app/packages/archivist/seed_csv
      - /usr/src/app/packages/archivist/node_modules
    ports:
      - "3000:3000"
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - rlc-net

  clarity-core:
    container_name: clarity-core
    # image: node:latest
    build:
      context: ./
      dockerfile: Dockerfile.clarity-core
    # working_dir: /usr/src/app
    restart: always
    # command: sh -c "npm install && npx tsc --outDir dist && npm start"
    # command: sh -c "yarn install && yarn dev"
    command: sh -c "yarn dev"
    volumes:
      - ./packages/clarity-core:/usr/src/app/packages/clarity-core
      - /usr/src/app/packages/clarity-core/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - archivist
    networks:
      rlc-net:
        aliases:
          - clarity-core

networks:
  rlc-net:
    name: rlc-net
    driver: bridge
