FROM node:latest as build
MAINTAINER Marc <marc@specular-occlusion>

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .
COPY packages_ts/constants ./packages_ts/constants
COPY packages_ts/types ./packages_ts/types
COPY packages_ts/clarity-core ./packages_ts/clarity-core

RUN yarn install --pure-lockfile --non-interactive

WORKDIR /usr/src/app/packages_ts/constants
RUN yarn build

WORKDIR /usr/src/app/packages_ts/types
RUN yarn build

WORKDIR /usr/src/app/packages_ts/clarity-core
RUN yarn build

# --------------------------------------

FROM node:latest

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

COPY --from=build /usr/src/app/packages_ts/constants/package.json /usr/src/app/packages_ts/constants/package.json
COPY --from=build /usr/src/app/packages_ts/constants/dist /usr/src/app/packages_ts/constants/dist

COPY --from=build /usr/src/app/packages_ts/types/package.json /usr/src/app/packages_ts/types/package.json
COPY --from=build /usr/src/app/packages_ts/types/dist /usr/src/app/packages_ts/types/dist

COPY --from=build /usr/src/app/packages_ts/clarity-core/package.json /usr/src/app/packages_ts/clarity-core/package.json

ENV NODE_ENV development

RUN yarn install --pure-lockfile --non-interactive

WORKDIR /usr/src/app/packages_ts/clarity-core

CMD ["yarn", "start:dev"]
