FROM node:latest as build
MAINTAINER Marc <marc@specular-occlusion>

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .
COPY packages/constants ./packages/constants

RUN yarn install --pure-lockfile --non-interactive

WORKDIR /usr/src/app/packages/constants
RUN yarn build

# --------------------------------------

FROM node:latest

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

COPY --from=build /usr/src/app/packages/constants/package.json /usr/src/app/packages/constants/package.json
COPY --from=build /usr/src/app/packages/constants/dist /usr/src/app/packages/constants/dist

COPY packages/clarity-core /usr/src/app/packages/clarity-core

ENV NODE_ENV development

RUN yarn install --pure-lockfile --non-interactive

WORKDIR /usr/src/app/packages/clarity-core

CMD ["yarn", "start:dev"]
