FROM node:latest

WORKDIR /app

COPY ./packages/archivist/package*.json ./

RUN npm install -g nodemon
RUN npm i -g @nestjs/cli

RUN npm install

COPY ./packages/archivist .

EXPOSE 3000

CMD ["nodemon", "--watch", ".", "--exec", "npm", "run", "start:dev"]
