FROM clojure:temurin-17-tools-deps
LABEL maintainer="Marc <xtof@relica.io>"

WORKDIR /usr/src/app

# For development, we don't copy files - they will be mounted as volumes
# in docker-compose.dev.yml for both common and clarity packages
# This allows for hot reloading of all code changes

WORKDIR /usr/src/app/packages_clj/clarity

# Expose both the application and nREPL ports
EXPOSE 2176
EXPOSE 7893

CMD ["clojure", "-M:dev"]
