version: "3.8"

services:
  clarity-core:
    image: node:14
    container_name: clarity-core
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    env_file:
      - .env
    command: sh -c "npm install && npx tsc --outDir dist && npm start"
    networks:
      rlc-net:
        aliases:
          - clarity-core

networks:
  rlc-net:
    external: true
