version: "3.8"

services:
  clarity-core:
    image: registry.gitlab.com/corpus-relica/clarity-core:${IMAGE_TAG}
    container_name: clarity-core
    ports:
      - "3001:3001"
    restart: always
    environment:
      RELICA_CLARITY_CORE_ALLOWED_ORIGIN: ${RELICA_CLARITY_CORE_ALLOWED_ORIGIN}
      RELICA_CLARITY_CORE_API_PORT: ${RELICA_CLARITY_CORE_API_PORT}
      RELICA_POSTGRES_HOST: ${RELICA_POSTGRES_HOST}
      RELICA_POSTGRES_USER: ${RELICA_POSTGRES_USER}
      RELICA_POSTGRES_PASSWORD: ${RELICA_POSTGRES_PASSWORD}
      RELICA_POSTGRES_DB_NAME: ${RELICA_POSTGRES_DB_NAME}
      RELICA_POSTGRES_PORT: ${RELICA_POSTGRES_PORT}
      RELICA_NEO4J_URL: ${RELICA_NEO4J_URL}
    networks:
      - rlc-net

networks:
  rlc-net:
    external: true
