version: '3.8'

services:
  archivist_ii:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3030:3000'
    container_name: archivist_ii
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
      - /app/node_modules
    command: ['npm', 'run', 'start:dev']
    networks:
      - rlc-net

networks:
  rlc-net:
    external: true
