name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure directory exists
            mkdir -p /root/systema_relica
            cd /root/systema_relica

            # Add GitHub's host key first
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Add GitHub SSH key with debug info
            if [ ! -f ~/.ssh/id_ed25519 ]; then
              echo "Setting up GitHub SSH key..."
              echo "${{ secrets.GH_SSH_KEY }}" > ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519
              echo "SSH key added. Contents of ~/.ssh:"
              ls -la ~/.ssh/
            fi

            # Test GitHub SSH connection
            ssh -vT git@github.com || true

            # Clone or pull repository
            if [ ! -d ".git" ]; then
              echo "Cloning repository..."
              git clone git@github.com:corpus-relica/systema-relica.git .
            else
              echo "Updating repository..."
              git fetch origin
              git reset --hard origin/main
            fi

            # Start the application
            echo "Starting docker compose..."
            docker-compose down || true
            docker-compose build
            docker-compose up -d
