name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Debug directory structure
        run: |
          pwd
          ls -la

      - name: Create deployment directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /root/systema_relica
            ls -la /root/systema_relica

      - name: Copy project files to server
        run: |
          echo "Creating tarball..."
          tar -v --warning=no-file-changed --exclude='.git' --exclude='node_modules' --exclude='.env' --exclude='*.log' -czf deploy.tar.gz .

          echo "Checking tarball..."
          ls -lh deploy.tar.gz

          echo "Copying to server..."
          scp -v deploy.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/root/systema_relica/

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/systema_relica
            ls -la
            echo "Extracting tarball..."
            tar xzf deploy.tar.gz
            echo "Running docker compose..."
            docker compose down || true
            docker compose build
            docker compose up -d
            echo "Cleaning up..."
            rm deploy.tar.gz
